# Generated by Django 5.0.3 on 2024-03-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0004_alter_categorymodel_category_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='news_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_news.categorymodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='news_description',
            field=models.TextField(null=True),
        ),
    ]
